### PR TITLE
Added Capacitor 3 compatibility

### PR DESCRIPTION
**Pull request by micahlt**
This PR lets this plugin be used in Capacitor 3 projects by fixing a missing dependency.  
Many thanks to https://github.com/capacitor-community/firebase-analytics/issues/55

### CODE REVIEW

**Comment by micahlt** [comment]
@hinddeep Would you please review this as soon as possible?  Without this PR or similar changes, the plugin is unusable for all projects utilizing Capacitor 3!

**Comment by micahlt** [comment]
Bump...

**Comment by doublechecker** [comment]
@micahlt nice work!

@hinddeep do you mind merging it? I really would like to use this plugin as there is no real alternative besides creating a custom solution but it needs to be compatible for Capacitor 3.

Cheers

**Comment by micahlt** [comment]
@doublechecker the original creator has gone inactive.  I published my fork on NPM if you'd like to use it though!  https://www.npmjs.com/package/@micahlt/capacitor-dark-mode

**Comment by hinddeep** [comment]
Hello, sorry for the delay. The pull request has been merged.

**Pull request merged**
